### ISSUE TITLE
Custom Mutation with Graffiti

### ISSUE THREAD

**Issue by TLevesque** [MarcBernat/Template-Graffiti-Mongoose#1]
Hi Marc, 
I'm looking to setup some custom queries and mutations in addition to the default ones of the graffiti schema, 
For example, I would like to create a mutation "createUser" which update 2 different collections when invoked, Graffiti looks nice, but there few documentation, do you have any advice?
Thank you very much for your help! 
Thibaut

**Comment by MarcBernat** [comment]
Hi @TLevesque,

Nowadays graffitti-mongoose doesn't have any methodology for extend the generated schema or include customs queries/mutations. But, even so, the official graffiti repo has RisingStack/graffiti-mongoose#64 open issue with how-to extend schemas. However, they are only tips. This isn't a final solution and could be difficult to maintain the code in a short term.

In my case, I switched to other ways to develop the GraphQL Server:

1. Creating the schema from the scratch. I reccomend this tutorial: [https://learngraphql.com/](https://learngraphql.com/) or learning from official docs.
2. Using an intermediate method. Like generators: [https://github.com/lucasbento/create-graphql](url) or this repo [https://github.com/apollographql/graphql-syntax](url) with a few utilities. 

In any case, here is the graffiti project for more info: 
[https://github.com/RisingStack/graffiti](url)

Now I'm learning GraphQL, so, feel free to ask anything. :smile:

**Comment by TLevesque** [comment]
Hi Marc, 
Thank you very much for your help and these great infos!!
Best,
Thibaut
